### ISSUE TITLE
Some mistake in cupy

### ISSUE THREAD

**Issue by wjcper2008** [slaue/genosolver#1]
Thanks for your work! I utilize geno algorithm to solve problem.  CPU mode: numpy is working perfect! But, when I import cupy instead numpy, it report error. 

Ubuntu 20.04 + cuda 11.6 + cudnn 8.5 + cupy-cuda11x 11.1.0 + genosolver newest

The code is generated from https://www.geno-project.org/ automaticly

dual support vector machines

generating random instance
solving ...
Traceback (most recent call last):
  File "/home/tt/Code/PyCode//solver.py", line 163, in <module>
    result, a = solve(K, c, y, np=np)
  File "/home/tt/Code/PyCode/solver.py", line 115, in solve
    NLP = GenoNLP(K, c, y, np)
  File "/home/tt/Code/PyCode/solver.py", line 56, in __init__
    assert dim == (1, )
AssertionError

Thanks for your help!

**Comment by slaue** [comment]
Thank you for reporting the bug. It is not an issue of cupy or numpy, it is really an error in the code. The field self.inf_array is being overwritten and this is wrong. It should read as

```python
    def max_step_size(self, x, d):
        np = self.np
        if self.constrained:
            step_ub = np.full(self.n, np.inf)
            step_lb = np.full(self.n, np.inf)
            step_ub = np.divide(self.ub - x, d, out=step_ub, where=d>0)
            step_lb = np.divide(self.lb - x, d, out=step_lb, where=d<0)
```
